- name: Demo on simple playbook raju
  hosts: all
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task1 raju'
    - name: Task2
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task2 raju'

